# Generated by Django 4.0.4 on 2022-10-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('identificacion', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cortetratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('identificacion', models.CharField(max_length=30, null=True)),
                ('dias', models.CharField(max_length=1000, null=True)),
                ('horas', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(max_length=30, null=True)),
                ('hora', models.CharField(max_length=30, null=True)),
                ('clienteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('corteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cortetratamiento')),
                ('empleadoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='empleado',
            field=models.ManyToManyField(through='cliente.Reserva', to='cliente.empleado'),
        ),
    ]
